In [1]:
import numpy as np

In [2]:
np.sqrt(10) #gives exact answer

np.float64(3.1622776601683795)

In [3]:
print(np.amin([25,30,57,18]))#prints minimum

18


In [4]:
print(np.amax([25,30,57,18]))#prints maximum

57


In [5]:
np.ceil(29.1) #rounds UP

np.float64(30.0)

In [6]:
np.ceil(np.sqrt(10))

np.float64(4.0)

In [7]:
np.ceil(np.sum(np.sqrt([5,10,15])))
#first square roots every item in list 
#then adds them up 
#then rounds up

np.float64(10.0)

In [8]:
abc = np.array([5,9,13])

In [9]:
type(abc)

numpy.ndarray

In [10]:
a=np.array([[1,2],[3,4],[4,5]])
print(a)
print("\n", a.dtype)

[[1 2]
 [3 4]
 [4 5]]

 int64


In [11]:
np.array([1,2,3],dtype=float) ## turn numbers to float

array([1., 2., 3.])

In [12]:
a=[1,2]
c=np.array(a)
print(c) # converted to an array

[1 2]


In [13]:
b=np.asarray(c)
print(b)

[1 2]


In [21]:
import numpy as np

In [22]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a=np.arange(10.5,20.4,2) # from 10.5 to under 20.4, incrimenting by 2
a

array([10.5, 12.5, 14.5, 16.5, 18.5])

In [26]:
a = np.arange(50,-1,-5) #decrement by 5 until -1
a

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

In [28]:
a = np.linspace(10,40,5) # 5 numbers equally apart from 10 to 40
a

array([10. , 17.5, 25. , 32.5, 40. ])

In [30]:
a = np.linspace(2.0,3.0,num=4,endpoint=True,retstep=True)
#start from 2, end at 3 (inclusive bc endpoint = true), 4 numbers, show the increment
a

(array([2.        , 2.33333333, 2.66666667, 3.        ]),
 np.float64(0.3333333333333333))

In [31]:
print(np.zeros([5])) #vector of zeros

[0. 0. 0. 0. 0.]


In [32]:
print(np.zeros([5,6]))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [33]:
print(np.ones([5,6]))

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [34]:
print(4*np.ones([5,6]))

[[4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4.]]


In [35]:
print(np.arange(30).reshape(5,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [38]:
np.random.seed(6) 
print(np.random.rand(10,6)) ## seed prints similar values between dif computers

[[0.89286015 0.33197981 0.82122912 0.04169663 0.10765668 0.59505206]
 [0.52981736 0.41880743 0.33540785 0.62251943 0.43814143 0.73588211]
 [0.51803641 0.5788586  0.6453551  0.99022427 0.8198582  0.41320093]
 [0.87626766 0.82375943 0.05447451 0.71863724 0.80217056 0.73640664]
 [0.70913175 0.54093685 0.12482417 0.9576473  0.4032563  0.21695116]
 [0.71727585 0.99420744 0.25561406 0.67130943 0.59900591 0.71733215]
 [0.93734953 0.35180977 0.2536341  0.40247251 0.74651072 0.72407057]
 [0.4061078  0.98937985 0.45049928 0.37380843 0.70962861 0.08245855]
 [0.39837292 0.77088097 0.76475098 0.28385938 0.18954219 0.47125096]
 [0.33480604 0.73473504 0.18910712 0.33110407 0.84422842 0.61502403]]


In [43]:
a = np.random.randint(5,20,10)
# numbers between 5 inclusive and 20 exclusive - 10 numbers
a

array([12, 13,  5, 15, 17, 18, 17, 13, 14,  7])

In [44]:
### OTP GENERATOR

In [47]:
def generate_otp():
    otp_in = np.random.randint(1000,10000,1)
    print("Hello, your OTP is ", otp_in)
    user_in = int(input("Please enter ur OTP here \n"))
    
    if otp_in==user_in:
        print("succesful")
    else:
        print("incorrect")

In [48]:
generate_otp()

Hello, your OTP is  [2021]


Please enter ur OTP here 
 2021


succesful
